# Double List: Transform describing the map frame in the ECEF frame as a translation and quaternion rotation
# Translation followed by rotation quaternion [x,y,z,rx,ry,rz,rw]
# Units: [m, m, m, rad, rad, rad, rad]
# Multi map transform (Continental Map)
# map_1_origin: [1104519.0366837296169, -4842076.8773120511323, 3988628.1614574785344, 0.27651989990159736577, -0.33059326932073251903, 0.81619708509143773512, 0.38479494997528296274]
#
# Demo map tf for single file
# map_1_origin: [1104607.93693215, -4842095.17489218, 3988579.69182129,0.430988762013745, 0.0693624996150827, # 0.0957255645270654,0.894580430683]
#
map_1_origin: [1104738.0865346656647,
-4842298.2076221462339,
3988206.9785127802752,
0.41980608326950596965,
0.036383273854429222516,
0.10667062595861162566,
0.90058896694948920025] 

# Integer: Update period of the map cell publication update
# Units: ms
update_rate: 2000

map_1_correction: [3.0,
1.0,
4.0,
0.0,
0.0,
0.0,
1.0] 